name: 'entr_warehouse'
version: '0.0.2'
require-dbt-version: [">=1.3.0", "<2.0.0"]
config-version: 2
profile: 'entr_warehouse'
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
vars:
  'dbt_date:time_zone': 'Etc/UTC'
  entr:
    dim_entr_asset_models: [seed_asset_plant, seed_asset_wind_turbine]
    fct_entr_time_series_models: [stg_entr_era5_sample, stg_entr_merra2_sample, stg_entr_plant_sample, stg_entr_scada_sample]
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
models:
  openoa:
    generic_openoa_tables:
      dim_asset_wind_turbine:
        +materialized: table
      dim_asset_wind_plant:
        +materialized: table
      dim_asset_wind_turbine:
        +materialized: table
    exposures:
      openoa_curtailment_and_availability:
        +materialized: table
      openoa_reanalysis:
        +materialized: table
      openoa_revenue_meter:
        +materialized: table
      openoa_wtg_scada:
        +materialized: table
