
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'entr_warehouse'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'entr_warehouse'

# for implementation of spark_utils package 
# NOTE: this should not be included when packaged! see https://github.com/dbt-labs/spark-utils#compatibility
dispatch:
    - macro_namespace: dbt_utils
      search_order: ['spark_utils', 'dbt_utils']

vars:
    'dbt_date:time_zone': 'Etc/UTC'
# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seed"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  entr_warehouse:
    +materialized: view

seeds:
  entr_warehouse:
    la_haute_borne_data_sample:
      +column_types:
        Wind_turbine_name: string
        Date_time: string
        Ba_avg: string
        P_avg:  string
        Ws_avg: string
        Va_avg: string
        Ot_avg: string
        Ya_avg: string
        Wa_avg: string
    la_haute_tag_mapping:
      +column_types:
        tag_name: string
        tag_is_new: string
        variable_name: string
        variable_long_name: string
        unit_long_name: string
        comment: string
    entr_tag_list:
      +column_types:
        entr_tag_id: integer
        entr_tag_name: string
        logical_node: string
        sensor_name: string
        presentation_name: string
        si_unit: string
        value_type: string
        data_type: string
        collector_type: string
