entr_warehouse:

  outputs:

    dev:
      type: bigquery
      method: service-account
      keyfile: dbt-gcloud-creds.json # set up this file so you can access gcloud
      project: entrhub
      dataset: entr_warehouse
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive

  target: dev
