{{
    config(materialized='table')
}}

-- OpenOA currently accepts data in the format generated by this projection
-- of the underlying entr data store.
{% set src_model = 'int_openoa_wtg_scada__flagged' %}
{% set keys = [ 'plant_id', 'plant_name', 'wind_turbine_id', 'wind_turbine_name', 'date_time'] %}
{% set tag_cols = dbt_utils.get_column_values(table=ref(src_model), column='entr_tag_name') %}

with
    src as (select * from {{ ref(src_model) }}),

piv as (
    select
        {{ jinja_list_to_sql(keys) }},
        {{  
            dbt_utils.pivot(
                column = 'entr_tag_name',
                values = tag_cols,
                then_value = 'tag_value',
                else_value = 'null',
                agg = 'avg',
                quote_identifiers = true) 
        }},
        {{  
            dbt_utils.pivot(
                column = 'entr_tag_name',
                values = tag_cols,
                then_value = 'flag_min_max_tag_value',
                else_value = 'null',
                agg = 'sum',
                quote_identifiers = true,
                prefix='flag_min_max_') 
        }},
        {{  
            dbt_utils.pivot(
                column = 'entr_tag_name',
                values = tag_cols,
                then_value = 'flag_stale_tag_value',
                else_value = 'null',
                agg = 'sum',
                quote_identifiers = true,
                prefix='flag_stale_') 
        }}
    from src
    {{ dbt_utils.group_by(n=keys|length) }}
)

select * from piv
