-- OpenOA currently accepts data in the format generated by this projection
-- of the underlying entr data store.
{{ config(materialized='table', sort='time') }}

WITH keyedSource as (
    SELECT concat(wind_turbine_name, "_", date_time) as key, *
    FROM {{ref('entr_data_standardized')}}
--     FROM `entrhub.entr_warehouse.entr_data_standardized`
)
SELECT
    MAX (wind_turbine_name) as id,
    CAST(MAX(date_time) as Timestamp) as time,
    CAST(MAX(IF(entr_tag_name = "WMET.HorWdSpd", tag_value, NULL)) as Numeric) AS wmet_wdspd_avg,
    CAST(MAX(IF(entr_tag_name = "WMET.HorWdDir", tag_value, NULL)) as Numeric) AS wmet_HorWdDir_avg,
    CAST(MAX(IF(entr_tag_name = "WMET.HorWdDirRel", tag_value, NULL)) as Numeric) AS wmet_VaneDir_avg,
    CAST(MAX(IF(entr_tag_name = "WNAC.Dir", tag_value, NULL)) as Numeric) AS wyaw_YwAng_avg,
    CAST(MAX(IF(entr_tag_name = "WTOW.GndCtlTmp", tag_value, NULL)) as Numeric) AS wmet_EnvTmp_avg,
    CAST(MAX(IF(entr_tag_name = "WROT.BlPthAngVal", tag_value, NULL)) as Numeric) AS wrot_BlPthAngVal1_avg,
FROM keyedSource
GROUP BY key
ORDER BY key